--liquibase formatted sql

--changeset boyd.timmerman:1

create table customers (
   customer_id   integer
      generated by default on null as identity,
   email_address varchar2(255 char) not null,
   full_name     varchar2(255 char) not null
);

alter table customers add constraint customers_pk primary key ( customer_id );

alter table customers add constraint customers_email_u unique ( email_address );

--rollback: drop table customers;
