--liquibase formatted sql

--changeset boyd.timmerman:1

create table inventory (
   inventory_id      integer
      generated by default on null as identity,
   store_id          integer not null,
   product_id        integer not null,
   product_inventory integer not null
);

alter table inventory add constraint inventory_pk primary key ( inventory_id );

alter table inventory add constraint inventory_store_product_u unique ( store_id,
                                                                        product_id );
                                                                        
--rollback: drop table inventory;