--liquibase formatted sql

--changeset boyd.timmerman:1

create table orders (
   order_id     integer
      generated by default on null as identity,
   order_tms    timestamp not null,
   customer_id  integer not null,
   order_status varchar2(10 char) not null,
   store_id     integer not null
);

alter table orders add constraint orders_pk primary key ( order_id );

alter table orders
   add constraint orders_status_c check ( order_status in ( 'CANCELLED',
                                                            'COMPLETE',
                                                            'OPEN',
                                                            'PAID',
                                                            'REFUNDED',
                                                            'SHIPPED' ) );

--rollback: drop table orders;
      