--liquibase formatted sql

--changeset boyd.timmerman:1

create table products (
   product_id         integer
      generated by default on null as identity,
   product_name       varchar2(255 char) not null,
   unit_price         number(10, 2),
   product_details    blob,
   product_image      blob,
   image_mime_type    varchar2(512 char),
   image_filename     varchar2(512 char),
   image_charset      varchar2(512 char),
   image_last_updated date
);

alter table products add constraint products_pk primary key ( product_id );

alter table products add constraint products_json_c check ( product_details is json );

--rollback: drop table products;
