--liquibase formatted sql

--changeset boyd.timmerman:1

create table shipments (
   shipment_id      integer
      generated by default on null as identity,
   store_id         integer not null,
   customer_id      integer not null,
   delivery_address varchar2(512 char) not null,
   shipment_status  varchar2(100 char) not null
);

alter table shipments add constraint shipments_pk primary key ( shipment_id );

alter table shipments
   add constraint shipment_status_c check ( shipment_status in ( 'CREATED',
                                                                 'SHIPPED',
                                                                 'IN-TRANSIT',
                                                                 'DELIVERED' ) );

--rollback: drop table shipments;
                                                                 