--liquibase formatted sql

--changeset boyd.timmerman:1

create table stores (
   store_id          integer
      generated by default on null as identity,
   store_name        varchar2(255 char) not null,
   web_address       varchar2(100 char),
   physical_address  varchar2(512 char),
   latitude          number(9, 6),
   longitude         number(9, 6),
   logo              blob,
   logo_mime_type    varchar2(512 char),
   logo_filename     varchar2(512 char),
   logo_charset      varchar2(512 char),
   logo_last_updated date
);

alter table stores add constraint stores_pk primary key ( store_id );

alter table stores add constraint store_name_u unique ( store_name );

alter table stores
   add constraint store_at_least_one_address_c check ( web_address is not null
       or physical_address is not null );

--rollback: drop table stores;
